// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://chequearapp.com.ar',
  redirects: {
    '/blog/aceptar-cheque-cliente-nuevo': '/blog/guia-aceptacion-cheques',
    '/blog/aceptar-cheque-empresa-desconocida': '/blog/guia-aceptacion-cheques',
    '/blog/aceptar-cheque-endosado': '/blog/guia-aceptacion-cheques',
    '/blog/aceptar-cheque-garantia': '/blog/guia-aceptacion-cheques',
    '/blog/aceptar-cheque-tercero': '/blog/guia-aceptacion-cheques',
    '/blog/como-llenar-cheque-correctamente': '/blog/guia-aceptacion-cheques',
    '/blog/errores-aceptar-cheques': '/blog/guia-aceptacion-cheques',
    '/blog/firma-cheque-incorrecta': '/blog/guia-aceptacion-cheques',
    '/blog/riesgos-aceptar-cheques-terceros': '/blog/guia-aceptacion-cheques',
    '/blog/verificar-cheque-antes-aceptar': '/blog/guia-aceptacion-cheques',
    '/blog/verificar-fondos-cheque': '/blog/guia-aceptacion-cheques',
    '/blog/cheque-180-dias-riesgo': '/blog/cheques-pago-diferido',
    '/blog/cheque-360-dias-conviene': '/blog/cheques-pago-diferido',
    '/blog/cheque-90-dias-riesgo': '/blog/cheques-pago-diferido',
    '/blog/cheque-comun-vs-diferido': '/blog/cheques-pago-diferido',
    '/blog/cheque-diferido-180-dias': '/blog/cheques-pago-diferido',
    '/blog/cheque-diferido-90-dias': '/blog/cheques-pago-diferido',
    '/blog/cheque-pago-diferido-explicado': '/blog/cheques-pago-diferido',
    '/blog/negociar-cheques-diferidos': '/blog/cheques-pago-diferido',
    '/blog/tasa-descuento-cheque-diferido': '/blog/cheques-pago-diferido',
    '/blog/banco-rechaza-cheque-motivos': '/blog/cheques-rechazados',
    '/blog/cheque-rebotado-como-saber': '/blog/cheques-rechazados',
    '/blog/cheque-rechazado-afecta-veraz': '/blog/cheques-rechazados',
    '/blog/cheque-rechazado-como-reclamar': '/blog/cheques-rechazados',
    '/blog/cheque-rechazado-cuantas-veces': '/blog/cheques-rechazados',
    '/blog/cheque-rechazado-que-significa': '/blog/cheques-rechazados',
    '/blog/consultar-cheques-rechazados-bcra': '/blog/cheques-rechazados',
    '/blog/multa-cheque-rechazado': '/blog/cheques-rechazados',
    '/blog/cheque-sin-fondos-que-hacer': '/blog/cheque-sin-fondos-consecuencias',
    '/blog/rechazo-cheque-sin-fondos-bcra': '/blog/cheque-sin-fondos-consecuencias',
    '/blog/cheque-cuenta-cerrada': '/blog/cheques-extraviados-denunciados',
    '/blog/cheque-denunciado-que-significa': '/blog/cheques-extraviados-denunciados',
    '/blog/cheque-denunciado-seguro': '/blog/cheques-extraviados-denunciados',
    '/blog/cheque-extraviado-pasos': '/blog/cheques-extraviados-denunciados',
    '/blog/cheque-al-portador-riesgos': '/blog/endoso-de-cheques',
    '/blog/cheque-endosado-varias-veces': '/blog/endoso-de-cheques',
    '/blog/cheque-no-a-la-orden': '/blog/endoso-de-cheques',
    '/blog/endoso-cheque-limite-firmas': '/blog/endoso-de-cheques',
    '/blog/endoso-cheques-guia': '/blog/endoso-de-cheques',
    '/blog/responsabilidad-endosante-cheque': '/blog/endoso-de-cheques',
    '/blog/diferencia-cheque-echeq': '/blog/echeq-electronico',
    '/blog/echeq-cheque-electronico': '/blog/echeq-electronico',
    '/blog/analisis-riesgo-cheques': '/blog/guia-legal-cheques',
    '/blog/analizar-riesgo-cheque': '/blog/guia-legal-cheques',
    '/blog/causas-rechazo-cheques': '/blog/guia-legal-cheques',
    '/blog/central-deudores-bcra': '/blog/guia-legal-cheques',
    '/blog/cheque-cancelado-que-significa': '/blog/guia-legal-cheques',
    '/blog/cheque-certificado-que-es': '/blog/guia-legal-cheques',
    '/blog/cheque-comercio-minorista': '/blog/guia-legal-cheques',
    '/blog/cheque-cruzado-explicado': '/blog/guia-legal-cheques',
    '/blog/cheque-empresa-quiebra': '/blog/guia-legal-cheques',
    '/blog/cheque-garantia-alquiler': '/blog/guia-legal-cheques',
    '/blog/cheque-historial-rechazos': '/blog/guia-legal-cheques',
    '/blog/cheque-mal-llenado-rechazo': '/blog/guia-legal-cheques',
    '/blog/cheque-monto-alto-precauciones': '/blog/guia-legal-cheques',
    '/blog/cheque-operacion-inmobiliaria': '/blog/guia-legal-cheques',
    '/blog/cheque-persona-veraz': '/blog/guia-legal-cheques',
    '/blog/cheque-posdatado-legal': '/blog/guia-legal-cheques',
    '/blog/cheque-posdatado-riesgo': '/blog/guia-legal-cheques',
    '/blog/cheque-proveedor-nuevo': '/blog/guia-legal-cheques',
    '/blog/cheque-sector-agro': '/blog/guia-legal-cheques',
    '/blog/cheque-sector-construccion': '/blog/guia-legal-cheques',
    '/blog/cheque-sin-fecha-validez': '/blog/guia-legal-cheques',
    '/blog/cheque-vencido-se-puede-cobrar': '/blog/guia-legal-cheques',
    '/blog/cheques-pymes-argentina': '/blog/guia-legal-cheques',
    '/blog/clearing-cheques-tiempos': '/blog/guia-legal-cheques',
    '/blog/cobrar-cheque-ventanilla': '/blog/guia-legal-cheques',
    '/blog/consultar-cuit-emisor-cheque': '/blog/guia-legal-cheques',
    '/blog/cuenta-corriente-requisitos-cheques': '/blog/guia-legal-cheques',
    '/blog/fraude-cheques-prevencion': '/blog/guia-legal-cheques',
    '/blog/guia-cheques-argentina': '/blog/guia-legal-cheques',
    '/blog/inhibicion-librar-cheques': '/blog/guia-legal-cheques',
    '/blog/plazos-legales-cheques': '/blog/guia-legal-cheques',
    '/blog/proteger-negocio-cheques': '/blog/guia-legal-cheques',
    '/blog/protesto-cheque-que-es': '/blog/guia-legal-cheques'
},
  integrations: [mdx(), sitemap()],
  vite: {
    plugins: [tailwindcss()]
  }
});